### ISSUE TITLE
Release 4.0 breaks on NC26

### ISSUE THREAD

**Issue by simonspa** [nextcloud/user_migration#421] opened 2023-05-17 06:20 UTC
After updating, opening the user settings yiels an "unknown error". The log k ones the following:

```
Declaration of OCA\UserMigration\Migrator\FilesMigrator::getEstimatedExportSize(OCP\IUser $user): int|float must be compatible with OCP\UserMigration\ISizeEstimationMigrator::getEstimatedExportSize(OCP\IUser $user): int at /var/www/nextcloud/apps/user_migration/lib/Migrator/FilesMigrator.php#95
```

On NC26 with PHP8.1

**Comment by tcitworld** [comment] 2023-05-17 06:25
Duplicate from #420

**Comment by simonspa** [comment] 2023-05-17 06:53
Hi @tcitworld 

I don't see how this is a duplicate of #420 - neither am I on NC25 not in PHP7.4.

This is NC26 with PHP Version: 8.1.18.

**Comment by tcitworld** [comment] 2023-05-17 06:56
Indeed, it's not exactly the same thing, but the cause is related. https://github.com/nextcloud/user_migration/pull/408 makes use of an NC27-only interface.

**Comment by Pytal** [comment] 2023-05-18 00:47
Closed by https://github.com/nextcloud/user_migration/pull/424

**Closed by Pytal** 2023-05-18 00:47 UTC
Labels: 1. to develop, bug

**Comment by Pytal** [comment] 2023-05-18 00:49
NC25 + 26 compatible version is v3.0.0

**Comment by simonspa** [comment] 2023-05-18 10:52
Is there a recovery path for the NC26 instances that have 4.0 installed already?

**Comment by Pytal** [comment] 2023-05-18 18:03
> Is there a recovery path for the NC26 instances that have 4.0 installed already?

Uninstall first should do the trick

```bash
occ app:remove user_migration
occ app:install user_migration
```

**Comment by simonspa** [comment] 2023-05-18 19:06
I still got served 4.0, probably because that's the highest version that claims support?

**Comment by Pytal** [comment] 2023-05-18 19:34
4.0.0 was removed for 26 https://apps.nextcloud.com/apps/user_migration

Can you verify that the `user_migration` app is not present in the apps directory after uninstalling?
